services:
  app:
    image: hashicorp/http-echo
    command: ["--listen=:80"]
    # volumes:
    #   - ./:/app
    depends_on:
      - postgres
      - redis
    expose:
      - 80
    env_file:
      - docker/.env
    privileged: true

  proxy:
    image: nginx:1.27.5
    depends_on:
      - app
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/proxy/certs:/etc/nginx/certs

  postgres:
    build:
      context: docker/postgres
    restart: always
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: application
      POSTGRES_PASSWORD: Rand0m!

  redis:
    image: redis:8.0.1

  dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - proxy
      - app
      - postgres
      - redis
    command: app:80 proxy:443 redis:6379 postgres:5432
